"""Make company_id NOT NULL in supplier_contacts

Revision ID: 274dbe33c8aa
Revises: d40cbc6156d6
Create Date: 2025-07-23 23:01:17.573916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '274dbe33c8aa'
down_revision = 'd40cbc6156d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Focando apenas na mudança do company_id para NOT NULL
    op.alter_column('supplier_contacts', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_contacts', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
