"""add_account_id_to_accounts_receivable

Revision ID: 75a869094852
Revises: fe480fec3c20
Create Date: 2025-08-03 15:23:12.465866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a869094852'
down_revision = 'fe480fec3c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_receivable', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts_receivable', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts_receivable', type_='foreignkey')
    op.drop_column('accounts_receivable', 'account_id')
    # ### end Alembic commands ###
