"""add_customers_table

Revision ID: add_customers_table
Revises: add_stock_branches_table
Create Date: 2025-07-26 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_customers_table'
down_revision = 'add_stock_branches_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('customer_type', sa.Enum('individual', 'company', name='customertype'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'blocked', name='customerstatus'), nullable=True),
    sa.Column('cpf', sa.VARCHAR(length=14), nullable=True),
    sa.Column('cnpj', sa.VARCHAR(length=18), nullable=True),
    sa.Column('rg', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ie', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('credit_limit', sa.INTEGER(), nullable=True),
    sa.Column('payment_terms', sa.VARCHAR(length=50), nullable=True),
    sa.Column('discount_percentage', sa.INTEGER(), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='customers_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ### 