"""add_marketplace_fields_to_products

Revision ID: add_marketplace_fields_to_products
Revises: add_product_management_tables
Create Date: 2025-07-25 21:57:32.394392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'marketplace_fields'
down_revision = 'add_product_management_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Adicionar campos específicos para Shopee
    op.add_column('products', sa.Column('shopee_category_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('shopee_category_name', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('shopee_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('shopee_warranty', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('shopee_brand_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('shopee_model_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('shopee_is_pre_order', sa.Boolean(), nullable=True, default=False))
    op.add_column('products', sa.Column('shopee_logistics', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    
    # Adicionar campos específicos para Mercado Livre
    op.add_column('products', sa.Column('mercadolivre_category_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('mercadolivre_category_name', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('mercadolivre_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('mercadolivre_warranty', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('mercadolivre_brand_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('mercadolivre_model_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('mercadolivre_condition', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('mercadolivre_listing_type', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('mercadolivre_shipping', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remover campos específicos para Shopee
    op.drop_column('products', 'shopee_logistics')
    op.drop_column('products', 'shopee_is_pre_order')
    op.drop_column('products', 'shopee_model_id')
    op.drop_column('products', 'shopee_brand_id')
    op.drop_column('products', 'shopee_warranty')
    op.drop_column('products', 'shopee_attributes')
    op.drop_column('products', 'shopee_category_name')
    op.drop_column('products', 'shopee_category_id')
    
    # Remover campos específicos para Mercado Livre
    op.drop_column('products', 'mercadolivre_shipping')
    op.drop_column('products', 'mercadolivre_listing_type')
    op.drop_column('products', 'mercadolivre_condition')
    op.drop_column('products', 'mercadolivre_model_id')
    op.drop_column('products', 'mercadolivre_brand_id')
    op.drop_column('products', 'mercadolivre_warranty')
    op.drop_column('products', 'mercadolivre_attributes')
    op.drop_column('products', 'mercadolivre_category_name')
    op.drop_column('products', 'mercadolivre_category_id')
    
    # ### end Alembic commands ### 