"""add_stock_branches_table

Revision ID: add_stock_branches_table
Revises: fix_sku_unique_constraint
Create Date: 2025-07-26 18:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_stock_branches_table'
down_revision = 'fix_sku_unique_constraint'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_branches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.INTEGER(), nullable=False),
    sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('current_stock', sa.INTEGER(), nullable=True),
    sa.Column('minimum_stock', sa.INTEGER(), nullable=True),
    sa.Column('maximum_stock', sa.INTEGER(), nullable=True),
    sa.Column('reserved_stock', sa.INTEGER(), nullable=True),
    sa.Column('warehouse_location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('shelf_location', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='stock_branches_branch_id_fkey'),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], name='stock_branches_sku_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_branches_pkey')
    )
    op.create_index('ix_stock_branches_id', 'stock_branches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_branches_id', table_name='stock_branches')
    op.drop_table('stock_branches')
    # ### end Alembic commands ### 