"""Add company_id and rename function to job_function in supplier_contacts

Revision ID: d40cbc6156d6
Revises: de08ace8cb88
Create Date: 2025-07-23 22:55:31.289336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd40cbc6156d6'
down_revision = 'de08ace8cb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Focando apenas nas mudanças do supplier_contacts
    op.add_column('supplier_contacts', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('supplier_contacts', sa.Column('job_function', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'supplier_contacts', 'companies', ['company_id'], ['id'])
    op.drop_column('supplier_contacts', 'function')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_contacts', sa.Column('function', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'supplier_contacts', type_='foreignkey')
    op.drop_column('supplier_contacts', 'job_function')
    op.drop_column('supplier_contacts', 'company_id')
    # ### end Alembic commands ###
